#!/bin/bash
# This environment file was generated by genconf.tcl script at 2022.02.01 13:06

export PRJFMT=pro
export ARCH=64
export SHORTCUT_HEADERS=ShortCut

export PRODUCTS_PATH=""

# Optional 3rd-parties switches
export HAVE_FREEIMAGE=false
export HAVE_FFMPEG=false
export HAVE_TBB=false
export HAVE_GLES2=false
export HAVE_VTK=false
export HAVE_ZLIB=false
export HAVE_LIBLZMA=false
export HAVE_E57=false
export HAVE_RAPIDJSON=false
export HAVE_OPENVR=false
export HAVE_OPENCL=false
export CHECK_QT4=false
export CHECK_JDK=false
export BUILD_Inspector=false

# Additional headers search paths
export CSF_OPT_INC="/usr/include/tcl8.6:/usr/include/freetype2"

# Additional libraries (64-bit) search paths
export CSF_OPT_LIB64="/opt/opencascade/oce-upstream-V7_5_0beta"

# Additional (64-bit) search paths
export CSF_OPT_BIN64=""
